## Система линейных алгебраичсеких уравнений

In [1]:
import numpy as np

### Задание 1

\begin{equation}
\left[\begin{array}{lll}{1} & {2} & {3} \\ {4} & {0} & {6} \\ {7} & {8} & {9}\end{array}\right] \cdot X=\left[\begin{array}{c}{12} \\ {2} \\ {1}\end{array}\right]
\end{equation}

In [2]:
a = np.matrix([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
a_ext = np.matrix([[1, 2, 3, 12], [4, 0, 6, 2], [7, 8, 9, 1]])
b = np.transpose(np.array([12, 2, 1]))

print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(a_ext))

3
3


система совместна и имеет единственное решение

In [3]:
det_a = np.linalg.det(a)
print(det_a)

59.999999999999986


In [4]:
x1 = np.matrix([[12, 2, 3], [2, 0, 6], [1, 8, 9]])
det_x1 = np.linalg.det(x1)
det_x1

-551.9999999999998

In [5]:
x2 = np.matrix([[1, 12, 3], [4, 2, 6], [7, 1, 9]])
det_x2= np.linalg.det(x2)
det_x2

54.00000000000003

In [6]:
x3 = np.matrix([[1, 2, 12], [4, 0, 2], [7, 8, 1]])
det_x3 = np.linalg.det(x3)
det_x3

388.00000000000006

In [7]:
X = np.matrix([det_x1/det_a, det_x2/det_a, det_x3/det_a])
X

matrix([[-9.2       ,  0.9       ,  6.46666667]])

In [8]:
a * X.T

matrix([[12.],
        [ 2.],
        [ 1.]])

### Задание 2

\begin{equation}
\begin{array}{l}{x+2 y-z=1} \\ {3 x-4 y=7} \\ {8 x-5 y+2 z=12} \\ {2 x-5 z=7} \\ {11 x+4 y-7 z=15}\end{array}
\end{equation}

In [76]:
A = np.matrix([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
b = np.matrix([1, 7, 12, 7, 15])

In [77]:
np.linalg.matrix_rank(A)

3

Столбцы линейно независимы, найдем псевдообратную матрицу по формуле:

\begin{equation}
A^{\sim 1}=\left(A^{*} \cdot A\right)^{-1} \cdot A^{*}
\end{equation}

In [78]:
A_inv = np.linalg.inv(A.T * A) * A.T
A_inv

matrix([[ 0.0184525 , -0.01309971,  0.06358533, -0.05827435,  0.0571557 ],
        [ 0.05588372, -0.11181622, -0.03160448, -0.12284939,  0.07073632],
        [ 0.03245479, -0.06855478,  0.06726537, -0.17860416, -0.00070046]])

In [79]:
X = A_inv * b.T
X

matrix([[ 1.13919353],
        [-0.90498444],
        [-0.9009803 ]])

In [84]:
print(X[0] + 2*X[1]-X[2])

[[0.23020495]]


### Задание 3

\begin{equation}
\left[\begin{array}{lll}{1} & {2} & {3} \\ {4} & {5} & {6} \\ {7} & {8} & {9}\end{array}\right] \cdot X=\left[\begin{array}{l}{12} \\ {2} \\ {1}\end{array}\right]
\end{equation}

In [13]:
a = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a_ext = np.matrix([[1, 2, 3, 12], [4, 5, 6, 2], [7, 8, 9, 1]])
b = np.transpose(np.array([12, 2, 1]))

In [14]:
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(a_ext))

2
3


ранг матрицы а не равен рангу расширенной матрицы - система не имеет решений

In [15]:
a_ext = np.matrix([[1, 2, 3, 3], [4, 5, 6, 2], [7, 8, 9, 1]])
b = np.transpose(np.array([3, 2, 1]))
print(np.linalg.matrix_rank(a_ext))

2


метод Гаусса

\begin{equation}
\left[\begin{array}{lll}{1} & {2} & {3} & {3} \\ {4} & {5} & {6} & {2} \\ {7} & {8} & {9} & {1}\end{array}\right]
\end{equation}

\begin{equation}
\left[\begin{array}{lll}{1} & {2} & {3} & {3} \\ {0} & {-3} & {-6} & {-10} \\ {0} & {-3} & {-6} & {-10}\end{array}\right]
\end{equation}

\begin{equation}
\left[\begin{array}{lll}{1} & {2} & {3} & {3} \\ {0} & {-3} & {-6} & {-10} \\ {0} & {0} & {0} & {0}\end{array}\right]
\end{equation}

x2 = 1/3 * (10 - 6*x3)
x1 = 3 - 3*x3 - 2/3 * (10 - 6*x3) = x3 - 11/3   

In [19]:
X_sol = ['x3 - 11/3', '10/3 - 2*x3', 'x3']
print(X_sol)

['x3 - 11/3', '10/3 - 2*x3', 'x3']


### Задание 5

\begin{equation}
\begin{array}{l}{x+2 y-z=1} \\ {8 x-5 y+2 z=12}\end{array}
\end{equation}

\begin{equation}
\begin{array}{l}{z = x+2 y - 1} \\ {y=10x-14}\end{array}
\end{equation}

\begin{equation}
\begin{array}{l}{z = 21x  - 29} \\ {y=10x-14}\end{array}
\end{equation}

In [40]:
X = ['x', '10x-14', '21x  - 29']
X

['x', '10x-14', '21x  - 29']

Q(x) = x^2 + 100x^2 - 280x + 196 + 441x^2 - 609x + 841 = 442x^2 - 889x + 1037

In [41]:
x0 = 889 / 884
x0

1.005656108597285

In [42]:
y0 = 10 * x0 - 14
y0

-3.9434389140271495

In [43]:
z0 = 21*x0 - 29
z0

-7.881221719457013

In [44]:
x0 + 2 * y0 - z0

0.9999999999999991

In [45]:
8 * x0 - 5 * y0 + 2 * z0

12.0

### Задание 4

\begin{equation}
\left[\begin{array}{ccc}{1} & {2} & {3} \\ {2} & {16} & {21} \\ {4} & {28} & {73}\end{array}\right]
\end{equation}

LU разложение

\begin{equation}
\left[\begin{array}{ccc}{1} & {2} & {3} \\ {2} & {12} & {15/12} \\ {4} & {20} & {73}\end{array}\right]
\end{equation}

\begin{equation}
\left[\begin{array}{ccc}{1} & {2} & {3} \\ {2} & {12} & {15/12} \\ {4} & {20} & {36}\end{array}\right]
\end{equation}

In [51]:
A = np.matrix([[1, 2, 3],[2, 16, 21], [4, 28, 73]])
L = np.matrix([[1, 0, 0],[2, 12, 0], [4, 20, 36]])
U = np.matrix([[1, 2, 3], [0, 1, 15/12], [0, 0, 1]])
print(L)
print(U)
print(L*U)

[[ 1  0  0]
 [ 2 12  0]
 [ 4 20 36]]
[[1.   2.   3.  ]
 [0.   1.   1.25]
 [0.   0.   1.  ]]
[[ 1.  2.  3.]
 [ 2. 16. 21.]
 [ 4. 28. 73.]]


In [50]:
print(np.linalg.matrix_rank(L*U))

3


\begin{equation}
b = \left[\begin{array}{ccc}{1} \\ {14}  \\ {60} \end{array}\right]
\end{equation}

In [53]:
A_ext = np.matrix([[1, 2, 3, 1],[2, 16, 21, 14], [4, 28, 73, 60]])
print(np.linalg.matrix_rank(A_ext))

3


Замена Y = UX
Решаем систему LY = b

In [60]:
Y = np.matrix([1, 1, 1])
print(f'Y={Y}')

Y=[[1 1 1]]


Тогда X:

In [61]:
X = np.matrix([-1.5, -0.25, 1])
print(X)

[[-1.5  -0.25  1.  ]]


In [62]:
print(A*np.transpose(X))

[[ 1.]
 [14.]
 [60.]]


### Задание 6

\begin{equation}
\left[\begin{array}{lll}{1} & {2} & {3} \\ {4} & {5} & {6} \\ {7} & {8} & {9}\end{array}\right] \cdot X=\left[\begin{array}{c}{2} \\ {5} \\ {11}\end{array}\right]
\end{equation}

In [93]:
A = np.matrix([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
A_ext = np.matrix([[1, 2, 3, 2],[4, 5, 6, 5], [7, 8, 9, 11]])
b = np.matrix([2, 5, 11])

In [94]:
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(A_ext))

2
3


 ранг А не равен рангу расширенной матрицы. Система несовместна. 

In [95]:
A_pinv = np.linalg.pinv(A)
A_pinv

matrix([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
        [-5.55555556e-02,  3.36727575e-17,  5.55555556e-02],
        [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [97]:
X = A_pinv * b.T
X

matrix([[ 1.25],
        [ 0.5 ],
        [-0.25]])

In [101]:
err = np.linalg.norm(A*X - b.T, ord=2)
err

1.2247448713915894