## Введение в линейную алгебру

In [1]:
import numpy as np

### Задание 5.1

In [3]:
k = 5
l = 3
a = np.array([1, 4, -8, 2])
b = np.transpose(a)

In [7]:
c1 = (k * l) * a
print(c1)
c2 = k * (l * a)
print(c2)

[  15   60 -120   30]
[  15   60 -120   30]


In [8]:
c3 = k * (a + b)
print(c3)
c4 = k * a + k * b
print(c4)

[ 10  40 -80  20]
[ 10  40 -80  20]


In [10]:
c5 = (k + l) * a
print(c5)
c6 = k * a + l * a
print(c6)

[  8  32 -64  16]
[  8  32 -64  16]


In [11]:
c7 = (a * b) * c1
print(c7)
c8 = a * (b * c1)
print(c8)

[   15   960 -7680   120]
[   15   960 -7680   120]


In [13]:
c9 = (a + b) * c1
print(c9)
c10 = a * c1 + b * c1
print(c10)

[  30  480 1920  120]
[  30  480 1920  120]


In [14]:
c11 = a * (b + c1)
print(c11)
c12 = a * b + a * c1
print(c12)

[  16  256 1024   64]
[  16  256 1024   64]


In [22]:
a = np.identity(5)
print(5 * a)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


обратная матрица для матрицы будет иметь вид 1/5 * a

проверим:

In [24]:
e = (5 * a) * (1/5 * a)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Задание 5.2

In [28]:
a = np.matrix([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [32]:
det_a = (2 * 6 * 7) + (4 * 8 *3) - (2 * 4 * 9) - (6 * 8 * 1)
det_a

60

In [31]:
det_a_proof = np.linalg.det(a)
det_a_proof

59.999999999999986

### Задание 5.3

In [33]:
M = np.transpose(np.matrix([[-48, 6, 32], [6, -12, 6], [12, -6, -8]]))
print(M)

[[-48   6  12]
 [  6 -12  -6]
 [ 32   6  -8]]


In [37]:
a_inv = 1/60 * M
print(a_inv)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2        -0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [38]:
print(a * a_inv)

[[ 1.00000000e+00 -2.77555756e-17 -4.00000000e-01]
 [-2.22044605e-16  1.00000000e+00  5.55111512e-17]
 [-7.77156117e-16  2.77555756e-17 -6.00000000e-01]]


In [35]:
print(np.linalg.inv(a))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


пример матрицы с рангом 1

In [40]:
a = np.matrix([[1, 2, 3, 4], [2, 4, 6, 8], [-7, -14, -21, -28], [3, 6, 9, 12]])
print(a)

[[  1   2   3   4]
 [  2   4   6   8]
 [ -7 -14 -21 -28]
 [  3   6   9  12]]


In [42]:
print(np.linalg.matrix_rank(a))

1


### Задание 5.4

In [45]:
a = np.array([1, 5])
b = np.array([2, 8])
c = (1 * 2) + (5 * 8)
c_pr = np.dot(a, b)
print(c)
print(c_pr)

42
42


In [46]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])

In [49]:
p_pr = np.linalg.det(np.matrix([a, b, c]))
print(p_pr)

228.50000000000009


In [50]:
p = 24 + (5 * 7 * 7) - (5 * 2 * 3) - 7 * 1.5
print(p)

228.5
